apps:
  chromadb:
    id: chromadb
    version: "1.0.0"
    repo_url: https://github.com/decyphertek-io/app-store
    folder_path: chromadb/
    executable: dist/chromadb.app
    release_url: https://github.com/decyphertek-io/app-store/releases/download/chromadb-v1.0.0/chromadb.app
    config: cdb-config.yaml
    config_path: ~/.decyphertek.ai/configs/
    install_path: ~/.decyphertek.ai/app-store/chromadb/
    enabled: true

  argostranslate:
    id: argostranslate
    version: "1.0.0"
    repo_url: https://github.com/decyphertek-io/app-store
    folder_path: argostranslate/
    executable: dist/argostranslate.app
    release_url: https://github.com/decyphertek-io/app-store/releases/download/argostranslate-v1.0.0/argostranslate.app
    install_path: ~/.decyphertek.ai/app-store/argostranslate/
    enabled: false

  ansible:
    id: ansible
    version: "1.0.0"
    repo_url: https://github.com/decyphertek-io/app-store
    folder_path: ansible/
    enabled: false
